apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.mygroup.example.com
spec:
  group: mygroup.example.com
  scope: Namespaced
  names:
    plural: myresources
    singular: myresource
    shortNames:
    - my
    - myres
    kind: MyResource
    categories:
    - all
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources: 
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              memory:
                x-kubernetes-int-or-string: true
          status:
            type: object
            properties:
              state:
                type: string
    additionalPrinterColumns:
      - name: image
        jsonPath: .spec.image
        type: string
      - name: memory
        jsonPath: .spec.memory
        type: string
      - name: age
        jsonPath: .metadata.creationTimestamp
        type: date

