# permissions for end users to view myresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: myresource-kb
    app.kubernetes.io/part-of: myresource-kb
    app.kubernetes.io/managed-by: kustomize
  name: myresource-viewer-role
rules:
- apiGroups:
  - mygroup.myid.dev
  resources:
  - myresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.myid.dev
  resources:
  - myresources/status
  verbs:
  - get
